from pathlib import Path
import json,hashlib
import numpy as np
import scipy
from scipy.special import i0e
assert np.__version__=='2.3.5' and scipy.__version__=='1.18.1'
root=Path(__file__).resolve().parents[1];cases=[]
for beta in [0.0,5.0,8.6,20.0,100.0,500.0,501.0,750.0,1000.0]:
 for periodic in [False,True]:
  n=33 if not periodic else 32;denom=n-1 if not periodic else n;alpha=denom/2;pos=(np.arange(n)-alpha)/alpha;r=np.sqrt(np.maximum(0,1-pos*pos));x=beta*r
  expected=np.exp(x-beta)*i0e(x)/i0e(beta)
  cases.append({'beta':beta,'periodic':periodic,'expected':expected.tolist()})
reference={'numpy':np.__version__,'scipy':scipy.__version__,'method':'independent scipy.special.i0e normalized Kaiser ratio; exp(x-beta)*i0e(x)/i0e(beta)'}
path=root/'fixtures/data/kaiser-precision.json';path.write_text(json.dumps({'reference':reference,'cases':cases,'tolerance':{'relative':1e-12,'absolute':1e-14}},indent=2)+'\n')
entries=',\n    '.join('('+str(c['beta'])+','+str(c['periodic']).lower()+',Vector('+','.join(repr(v) for v in c['expected'])+'))' for c in cases)
source='''package signal4s.fft

/** Frozen independent SciPy1.18.1/NumPy2.3.5 i0e ratios; generated by
  * fixtures/generate-kaiser-reference.py. Reference hash: SHA.
  */
class KaiserPrecisionSuite extends munit.FunSuite:
  private val cases=Vector(
    ENTRIES)
  for (beta,periodic,expected)<-cases do
    test(s"independent scaled I0 Kaiser beta=$beta periodic=$periodic"):
      val convention=if periodic then WindowConvention.Periodic else WindowConvention.Symmetric
      val w=Window.fromSpec(WindowSpec.Kaiser(expected.size,beta,convention)).toOption.get
      for i<-expected.indices do
        assertEqualsDouble(w.taps(i),expected(i),1e-14+math.abs(expected(i))*1e-12)
        assert(w.taps(i).isFinite && w.taps(i)>=0 && w.taps(i)<=1.0+1e-14)
  test("extreme finite beta remains finite and invalid beta refuses"):
    val w=Window.fromSpec(WindowSpec.Kaiser(33,Double.MaxValue,WindowConvention.Symmetric)).toOption.get
    assertEquals(w.taps(16),1.0)
    assert(w.taps.toSeq.forall(_.isFinite))
    assert(Window.fromSpec(WindowSpec.Kaiser(33,Double.NaN,WindowConvention.Symmetric)).isLeft)
'''.replace('ENTRIES',entries).replace('SHA',hashlib.sha256(path.read_bytes()).hexdigest())
(root/'modules/fft/shared/src/test/scala/signal4s/fft/KaiserPrecisionSuite.scala').write_text(source)
print('Frozen18 portable independent Kaiser cases and one extreme-beta refusal case.')
